//-------------------------------------------------------------
// Team Identification Block
// Author 1:	            Lisa Sun
// Student ID:	            *20300925
// E-Mail:		            lsun1@uco.edu
// Student 1 CRN:           22142, Spring 2023
// Author 2:	            Philip Yong
// Student ID:	            *20512220
// E-Mail:		            pyong@uco.edu
// Student 2 CRN:	        21502, Spring 2023
// Course:		            CMSC 4023 - Programming Languages
// Project:	 	            p02
// Due:		 	            February 27, 2023
// Project Account Number:	tt048
//--------------------------------------------------------------
#ifndef p02par_h
#define p02par_h 1
//--------------------------------------------------------------------
// File p02par.h defines the interface to the parser generated by
// yacc.
//--------------------------------------------------------------------
// Author: Thomas R. Turner
// E-Mail: trturner.uco.edu
// Date: January, 2015
//--------------------------------------------------------------------
// Copyright January, 2015 by Thomas R. Turner
// Do not reproduce without permission from Thomas R. Turner.
//--------------------------------------------------------------------
// Application include files
//--------------------------------------------------------------------
#include "p02lex.h"
//--------------------------------------------------------------------
//--------------------------------------------------------------------
// Function yyparse is the parser generated by yacc.
//--------------------------------------------------------------------
#ifdef __cplusplus
extern "C"
#endif
    int
    yyparse(void);
#endif
class Parser : public Lexer
{
public:
    Parser(FILE *i) : Lexer(i) {}
    int Parse(void) { return yyparse(); }
};